# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: End-to-end tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses:
          actions/checkout@v1
          # Install NPM dependencies, cache them correctly
          # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000'
          command: npm run cy:ci:test
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
  sonarcloud:
    needs: cypress-run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    needs: cypress-run
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install node module
        run: npm ci
      - name: Build the website
        run: npm run build
      - name: Deploy Surge
        uses: yg/deploy-surge@v1.0.0
        with:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
